//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company_test.dbo_connt
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Emp1
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Qalification { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        [MaxLength(10,ErrorMessage = "Cannot be longer than 10 characters")]
        public string Status { get; set; }
    }
}
